name: moviedb
description: Simple Movie DB app

publish_to: 'none'

version: 0.9.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ^3.3.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  provider: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: "launcher_icon"
  image_path_android: "icon/android.png"
  adaptive_icon_background: #0e1324
  adaptive_icon_foreground: "icon/android.png"
  min_sdk_android: 23

  ios: true
  image_path_ios: "icon/ios.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: sf
      fonts:
        - asset: assets/fonts/sf/SF-Pro-Display-Bold.otf
          weight: 700
        - asset: assets/fonts/sf/SF-Pro-Display-Medium.otf
          weight: 600
        - asset: assets/fonts/sf/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: assets/fonts/sf/SF-Pro-Display-Regular.otf
          weight: 400
        - asset: assets/fonts/sf/SF-Pro-Display-Thin.otf
          weight: 300