name: moviedb
description: Simple Movie DB app

publish_to: 'none'

version: 0.9.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ^3.0.5

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: "launcher_icon"
  image_path_android: "icon/android.png"
  adaptive_icon_background: #0e1324
  adaptive_icon_foreground: "icon/android.png"
  min_sdk_android: 23

  ios: true
  image_path_ios: "icon/ios.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
